// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    name,
    responsible_name,
    responsible_whatsapp,
    note
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, responsible_name, responsible_whatsapp, note, active, created_at, updated_at
`

type CreateClientParams struct {
	Name                string      `json:"name"`
	ResponsibleName     pgtype.Text `json:"responsible_name"`
	ResponsibleWhatsapp pgtype.Text `json:"responsible_whatsapp"`
	Note                pgtype.Text `json:"note"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.ResponsibleName,
		arg.ResponsibleWhatsapp,
		arg.Note,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ResponsibleName,
		&i.ResponsibleWhatsapp,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientBalance = `-- name: GetClientBalance :one
SELECT client_id, orders_total_cents, payments_total_cents, balance_cents
FROM client_balances
WHERE client_id = $1
`

func (q *Queries) GetClientBalance(ctx context.Context, clientID pgtype.UUID) (ClientBalance, error) {
	row := q.db.QueryRow(ctx, getClientBalance, clientID)
	var i ClientBalance
	err := row.Scan(
		&i.ClientID,
		&i.OrdersTotalCents,
		&i.PaymentsTotalCents,
		&i.BalanceCents,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, responsible_name, responsible_whatsapp, note, active, created_at, updated_at
FROM clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ResponsibleName,
		&i.ResponsibleWhatsapp,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT
    c.id, c.name, c.responsible_name, c.responsible_whatsapp, c.note, c.active, c.created_at, c.updated_at,
    cb.balance_cents
FROM clients c
JOIN client_balances cb ON cb.client_id = c.id
WHERE $1::text IS NULL
   OR c.name ILIKE '%' || $1::text || '%'
   OR c.responsible_name ILIKE '%' || $1::text || '%'
ORDER BY c.active DESC, c.name ASC
`

type ListClientsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	ResponsibleName     pgtype.Text        `json:"responsible_name"`
	ResponsibleWhatsapp pgtype.Text        `json:"responsible_whatsapp"`
	Note                pgtype.Text        `json:"note"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	BalanceCents        int64              `json:"balance_cents"`
}

func (q *Queries) ListClients(ctx context.Context, search pgtype.Text) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsRow
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ResponsibleName,
			&i.ResponsibleWhatsapp,
			&i.Note,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsWithDebt = `-- name: ListClientsWithDebt :many
SELECT
    c.id, c.name, c.responsible_name, c.responsible_whatsapp, c.note, c.active, c.created_at, c.updated_at,
    cb.balance_cents
FROM clients c
JOIN client_balances cb ON cb.client_id = c.id
WHERE cb.balance_cents > 0
ORDER BY cb.balance_cents DESC, c.name ASC
`

type ListClientsWithDebtRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	ResponsibleName     pgtype.Text        `json:"responsible_name"`
	ResponsibleWhatsapp pgtype.Text        `json:"responsible_whatsapp"`
	Note                pgtype.Text        `json:"note"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	BalanceCents        int64              `json:"balance_cents"`
}

func (q *Queries) ListClientsWithDebt(ctx context.Context) ([]ListClientsWithDebtRow, error) {
	rows, err := q.db.Query(ctx, listClientsWithDebt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsWithDebtRow
	for rows.Next() {
		var i ListClientsWithDebtRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ResponsibleName,
			&i.ResponsibleWhatsapp,
			&i.Note,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET
    name = $2,
    responsible_name = $3,
    responsible_whatsapp = $4,
    note = $5,
    active = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, responsible_name, responsible_whatsapp, note, active, created_at, updated_at
`

type UpdateClientParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	ResponsibleName     pgtype.Text `json:"responsible_name"`
	ResponsibleWhatsapp pgtype.Text `json:"responsible_whatsapp"`
	Note                pgtype.Text `json:"note"`
	Active              bool        `json:"active"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.ResponsibleName,
		arg.ResponsibleWhatsapp,
		arg.Note,
		arg.Active,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ResponsibleName,
		&i.ResponsibleWhatsapp,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
