// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	ResponsibleName     pgtype.Text        `json:"responsible_name"`
	ResponsibleWhatsapp pgtype.Text        `json:"responsible_whatsapp"`
	Note                pgtype.Text        `json:"note"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ClientBalance struct {
	ClientID           pgtype.UUID `json:"client_id"`
	OrdersTotalCents   int64       `json:"orders_total_cents"`
	PaymentsTotalCents int64       `json:"payments_total_cents"`
	BalanceCents       int64       `json:"balance_cents"`
}

type Order struct {
	ID           pgtype.UUID        `json:"id"`
	ClientID     pgtype.UUID        `json:"client_id"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	Note         pgtype.Text        `json:"note"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy  pgtype.UUID        `json:"cancelled_by"`
	CancelReason pgtype.Text        `json:"cancel_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	ProductName    string             `json:"product_name"`
	Quantity       int32              `json:"quantity"`
	UnitPriceCents int64              `json:"unit_price_cents"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	ClientID      pgtype.UUID        `json:"client_id"`
	AmountCents   int64              `json:"amount_cents"`
	Note          pgtype.Text        `json:"note"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy   pgtype.UUID        `json:"cancelled_by"`
	CancelReason  pgtype.Text        `json:"cancel_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PaymentMethod string             `json:"payment_method"`
}

type Product struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	PriceCents int64              `json:"price_cents"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CategoryID pgtype.UUID        `json:"category_id"`
}

type ProductCategory struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
