// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET
    cancelled_at = now(),
    cancelled_by = $2,
    cancel_reason = $3
WHERE id = $1
  AND cancelled_at IS NULL
RETURNING id, client_id, created_by, note, cancelled_at, cancelled_by, cancel_reason, created_at
`

type CancelOrderParams struct {
	ID           pgtype.UUID `json:"id"`
	CancelledBy  pgtype.UUID `json:"cancelled_by"`
	CancelReason pgtype.Text `json:"cancel_reason"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.CancelledBy, arg.CancelReason)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CreatedBy,
		&i.Note,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    client_id,
    created_by,
    note
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, client_id, created_by, note, cancelled_at, cancelled_by, cancel_reason, created_at
`

type CreateOrderParams struct {
	ClientID  pgtype.UUID `json:"client_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
	Note      pgtype.Text `json:"note"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.ClientID, arg.CreatedBy, arg.Note)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CreatedBy,
		&i.Note,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    product_id,
    product_name,
    quantity,
    unit_price_cents
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, order_id, product_id, product_name, quantity, unit_price_cents, created_at
`

type CreateOrderItemParams struct {
	OrderID        pgtype.UUID `json:"order_id"`
	ProductID      pgtype.UUID `json:"product_id"`
	ProductName    string      `json:"product_name"`
	Quantity       int32       `json:"quantity"`
	UnitPriceCents int64       `json:"unit_price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, client_id, created_by, note, cancelled_at, cancelled_by, cancel_reason, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CreatedBy,
		&i.Note,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const listClientOrders = `-- name: ListClientOrders :many
SELECT
    o.id, o.client_id, o.created_by, o.note, o.cancelled_at, o.cancelled_by, o.cancel_reason, o.created_at,
    COALESCE(SUM(oi.unit_price_cents * oi.quantity), 0)::bigint AS total_cents
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
WHERE o.client_id = $1
GROUP BY o.id
ORDER BY o.created_at DESC
`

type ListClientOrdersRow struct {
	ID           pgtype.UUID        `json:"id"`
	ClientID     pgtype.UUID        `json:"client_id"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	Note         pgtype.Text        `json:"note"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy  pgtype.UUID        `json:"cancelled_by"`
	CancelReason pgtype.Text        `json:"cancel_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	TotalCents   int64              `json:"total_cents"`
}

func (q *Queries) ListClientOrders(ctx context.Context, clientID pgtype.UUID) ([]ListClientOrdersRow, error) {
	rows, err := q.db.Query(ctx, listClientOrders, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientOrdersRow
	for rows.Next() {
		var i ListClientOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CreatedBy,
			&i.Note,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.TotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, product_name, quantity, unit_price_cents, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
