// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPayment = `-- name: CancelPayment :one
UPDATE payments
SET
    cancelled_at = now(),
    cancelled_by = $2,
    cancel_reason = $3
WHERE id = $1
  AND cancelled_at IS NULL
RETURNING id, client_id, amount_cents, note, created_by, cancelled_at, cancelled_by, cancel_reason, created_at
`

type CancelPaymentParams struct {
	ID           pgtype.UUID `json:"id"`
	CancelledBy  pgtype.UUID `json:"cancelled_by"`
	CancelReason pgtype.Text `json:"cancel_reason"`
}

func (q *Queries) CancelPayment(ctx context.Context, arg CancelPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, cancelPayment, arg.ID, arg.CancelledBy, arg.CancelReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.AmountCents,
		&i.Note,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    client_id,
    amount_cents,
    note,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, client_id, amount_cents, note, created_by, cancelled_at, cancelled_by, cancel_reason, created_at
`

type CreatePaymentParams struct {
	ClientID    pgtype.UUID `json:"client_id"`
	AmountCents int64       `json:"amount_cents"`
	Note        pgtype.Text `json:"note"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ClientID,
		arg.AmountCents,
		arg.Note,
		arg.CreatedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.AmountCents,
		&i.Note,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, client_id, amount_cents, note, created_by, cancelled_at, cancelled_by, cancel_reason, created_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.AmountCents,
		&i.Note,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const listClientPayments = `-- name: ListClientPayments :many
SELECT id, client_id, amount_cents, note, created_by, cancelled_at, cancelled_by, cancel_reason, created_at
FROM payments
WHERE client_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClientPayments(ctx context.Context, clientID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listClientPayments, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.AmountCents,
			&i.Note,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
