// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductCategory = `-- name: CreateProductCategory :one
INSERT INTO product_categories (
    name
) VALUES (
    $1
)
RETURNING id, name, active, created_at, updated_at
`

func (q *Queries) CreateProductCategory(ctx context.Context, name string) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, createProductCategory, name)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductCategoryByID = `-- name: GetProductCategoryByID :one
SELECT id, name, active, created_at, updated_at
FROM product_categories
WHERE id = $1
`

func (q *Queries) GetProductCategoryByID(ctx context.Context, id pgtype.UUID) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, getProductCategoryByID, id)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProductCategories = `-- name: ListActiveProductCategories :many
SELECT id, name, active, created_at, updated_at
FROM product_categories
WHERE active = true
ORDER BY name ASC
`

func (q *Queries) ListActiveProductCategories(ctx context.Context) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listActiveProductCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCategories = `-- name: ListProductCategories :many
SELECT id, name, active, created_at, updated_at
FROM product_categories
WHERE $1::text IS NULL
   OR name ILIKE '%' || $1::text || '%'
ORDER BY active DESC, name ASC
`

func (q *Queries) ListProductCategories(ctx context.Context, search pgtype.Text) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listProductCategories, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductCategory = `-- name: UpdateProductCategory :one
UPDATE product_categories
SET
    name = $2,
    active = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, active, created_at, updated_at
`

type UpdateProductCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Active bool        `json:"active"`
}

func (q *Queries) UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, updateProductCategory, arg.ID, arg.Name, arg.Active)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
