// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    category,
    price_cents
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, category, price_cents, active, created_at, updated_at
`

type CreateProductParams struct {
	Name       string      `json:"name"`
	Category   pgtype.Text `json:"category"`
	PriceCents int64       `json:"price_cents"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Category, arg.PriceCents)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, category, price_cents, active, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, category, price_cents, active, created_at, updated_at
FROM products
WHERE active = true
ORDER BY category ASC NULLS LAST, name ASC
`

func (q *Queries) ListActiveProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.PriceCents,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, category, price_cents, active, created_at, updated_at
FROM products
WHERE $1::text IS NULL
   OR name ILIKE '%' || $1::text || '%'
   OR category ILIKE '%' || $1::text || '%'
ORDER BY active DESC, category ASC NULLS LAST, name ASC
`

func (q *Queries) ListProducts(ctx context.Context, search pgtype.Text) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.PriceCents,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = $2,
    category = $3,
    price_cents = $4,
    active = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, category, price_cents, active, created_at, updated_at
`

type UpdateProductParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Category   pgtype.Text `json:"category"`
	PriceCents int64       `json:"price_cents"`
	Active     bool        `json:"active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.PriceCents,
		arg.Active,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
