// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
WITH inserted AS (
    INSERT INTO products (
        name,
        category_id,
        price_cents
    ) VALUES (
        $1,
        $3::uuid,
        $2
    )
    RETURNING id, name, price_cents, active, created_at, updated_at, category_id
)
SELECT
    inserted.id,
    inserted.name,
    inserted.category_id,
    product_categories.name AS category_name,
    inserted.price_cents,
    inserted.active,
    inserted.created_at,
    inserted.updated_at
FROM inserted
LEFT JOIN product_categories ON product_categories.id = inserted.category_id
`

type CreateProductParams struct {
	Name       string      `json:"name"`
	PriceCents int64       `json:"price_cents"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type CreateProductRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CategoryName pgtype.Text        `json:"category_name"`
	PriceCents   int64              `json:"price_cents"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceCents, arg.CategoryID)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    products.id,
    products.name,
    products.category_id,
    product_categories.name AS category_name,
    products.price_cents,
    products.active,
    products.created_at,
    products.updated_at
FROM products
LEFT JOIN product_categories ON product_categories.id = products.category_id
WHERE products.id = $1
`

type GetProductByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CategoryName pgtype.Text        `json:"category_name"`
	PriceCents   int64              `json:"price_cents"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT
    products.id,
    products.name,
    products.category_id,
    product_categories.name AS category_name,
    products.price_cents,
    products.active,
    products.created_at,
    products.updated_at
FROM products
LEFT JOIN product_categories ON product_categories.id = products.category_id
LEFT JOIN (
    SELECT
        oi.product_id,
        COALESCE(SUM(oi.quantity), 0)::bigint AS total_ordered_quantity
    FROM order_items oi
    JOIN orders o ON o.id = oi.order_id
    WHERE o.cancelled_at IS NULL
    GROUP BY oi.product_id
) product_popularity ON product_popularity.product_id = products.id
WHERE products.active = true
ORDER BY
    COALESCE(product_popularity.total_ordered_quantity, 0) DESC,
    product_categories.name ASC NULLS LAST,
    products.name ASC
`

type ListActiveProductsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CategoryName pgtype.Text        `json:"category_name"`
	PriceCents   int64              `json:"price_cents"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveProducts(ctx context.Context) ([]ListActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProductsRow
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.PriceCents,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    products.id,
    products.name,
    products.category_id,
    product_categories.name AS category_name,
    products.price_cents,
    products.active,
    products.created_at,
    products.updated_at
FROM products
LEFT JOIN product_categories ON product_categories.id = products.category_id
WHERE $1::text IS NULL
   OR products.name ILIKE '%' || $1::text || '%'
   OR product_categories.name ILIKE '%' || $1::text || '%'
ORDER BY products.active DESC, product_categories.name ASC NULLS LAST, products.name ASC
`

type ListProductsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CategoryName pgtype.Text        `json:"category_name"`
	PriceCents   int64              `json:"price_cents"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProducts(ctx context.Context, search pgtype.Text) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.PriceCents,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
WITH updated AS (
    UPDATE products
    SET
        name = $2,
        category_id = $5::uuid,
        price_cents = $3,
        active = $4,
        updated_at = now()
    WHERE products.id = $1
    RETURNING id, name, price_cents, active, created_at, updated_at, category_id
)
SELECT
    updated.id,
    updated.name,
    updated.category_id,
    product_categories.name AS category_name,
    updated.price_cents,
    updated.active,
    updated.created_at,
    updated.updated_at
FROM updated
LEFT JOIN product_categories ON product_categories.id = updated.category_id
`

type UpdateProductParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	PriceCents int64       `json:"price_cents"`
	Active     bool        `json:"active"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type UpdateProductRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CategoryName pgtype.Text        `json:"category_name"`
	PriceCents   int64              `json:"price_cents"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.PriceCents,
		arg.Active,
		arg.CategoryID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
