// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error)
	CancelPayment(ctx context.Context, arg CancelPaymentParams) (Payment, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateProductCategory(ctx context.Context, name string) (ProductCategory, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetClientBalance(ctx context.Context, clientID pgtype.UUID) (ClientBalance, error)
	GetClientByID(ctx context.Context, id pgtype.UUID) (Client, error)
	GetDailyOrdersTotal(ctx context.Context, arg GetDailyOrdersTotalParams) (int64, error)
	GetDailyPaymentsTotal(ctx context.Context, arg GetDailyPaymentsTotalParams) (int64, error)
	GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (GetProductByIDRow, error)
	GetProductCategoryByID(ctx context.Context, id pgtype.UUID) (ProductCategory, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListActiveProductCategories(ctx context.Context) ([]ProductCategory, error)
	ListActiveProducts(ctx context.Context) ([]ListActiveProductsRow, error)
	ListClientOrders(ctx context.Context, clientID pgtype.UUID) ([]ListClientOrdersRow, error)
	ListClientPayments(ctx context.Context, clientID pgtype.UUID) ([]Payment, error)
	ListClients(ctx context.Context, search pgtype.Text) ([]ListClientsRow, error)
	ListClientsWithDebt(ctx context.Context) ([]ListClientsWithDebtRow, error)
	ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	ListProductCategories(ctx context.Context, search pgtype.Text) ([]ProductCategory, error)
	ListProducts(ctx context.Context, search pgtype.Text) ([]ListProductsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	RevokeUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
