// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyOrdersTotal = `-- name: GetDailyOrdersTotal :one
SELECT
    COALESCE(SUM(oi.unit_price_cents * oi.quantity), 0)::bigint AS total_cents
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
WHERE o.cancelled_at IS NULL
  AND o.created_at >= $1
  AND o.created_at < $2
`

type GetDailyOrdersTotalParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetDailyOrdersTotal(ctx context.Context, arg GetDailyOrdersTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDailyOrdersTotal, arg.CreatedAt, arg.CreatedAt_2)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const getDailyPaymentsTotal = `-- name: GetDailyPaymentsTotal :one
SELECT
    COALESCE(SUM(amount_cents), 0)::bigint AS total_cents
FROM payments
WHERE cancelled_at IS NULL
  AND created_at >= $1
  AND created_at < $2
`

type GetDailyPaymentsTotalParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetDailyPaymentsTotal(ctx context.Context, arg GetDailyPaymentsTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDailyPaymentsTotal, arg.CreatedAt, arg.CreatedAt_2)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT
    COALESCE(SUM(balance_cents), 0)::bigint AS open_balance_cents,
    COUNT(*) FILTER (WHERE balance_cents > 0)::bigint AS clients_with_debt,
    COUNT(*)::bigint AS total_clients
FROM client_balances
`

type GetDashboardSummaryRow struct {
	OpenBalanceCents int64 `json:"open_balance_cents"`
	ClientsWithDebt  int64 `json:"clients_with_debt"`
	TotalClients     int64 `json:"total_clients"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary)
	var i GetDashboardSummaryRow
	err := row.Scan(&i.OpenBalanceCents, &i.ClientsWithDebt, &i.TotalClients)
	return i, err
}
